--- Documentation/Makefile
+++ Documentation/Makefile
@@ -1,4 +1,3 @@
-subdir-y := accounting arm auxdisplay blackfin connector \
-	filesystems filesystems ia64 laptops mic misc-devices \
-	networking pcmcia prctl ptp spi timers vDSO video4linux \
-	watchdog
+subdir-y := accounting auxdisplay blackfin connector \
+	filesystems filesystems ia64 laptops misc-devices \
+	pcmcia prctl ptp spi timers vDSO video4linux watchdog
